In [40]:
import pandas as pd
import numpy as np

data = pd.read_csv('cleaned_data.csv')
data = np.array(data)


def ndarray_describe(ndarray):
    ndarray = pd.DataFrame(ndarray)
    ndarray = ndarray.describe()
    ndarray = np.array(ndarray)
    return(ndarray)

print(ndarray_describe(data))

def ndarray_info(ndarray):
    ndarray = pd.DataFrame(ndarray)
    ndarray = ndarray.info()
    ndarray = np.array(ndarray)
    return(ndarray)

print(ndarray_info(data))

[[6041 6041 5968.0 6039.0 6041.0 6041.0 6033.0 5989.0 6041.0]
 [102 756 748.0 2316.0 809.0 838.0 1276.0 1950.0 3930.0]
 ['Carp' '06/09/93' 15.0 100.0 37.31671 77.25859 79.0 0.69 0.0]
 [861 84 59.0 58.0 179.0 179.0 77.0 18.0 220.0]]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6041 entries, 0 to 6040
Data columns (total 9 columns):
0    6041 non-null object
1    6041 non-null object
2    5968 non-null object
3    6039 non-null object
4    6041 non-null object
5    6041 non-null object
6    6033 non-null object
7    5989 non-null object
8    6041 non-null object
dtypes: object(9)
memory usage: 424.8+ KB
None
